# Generated by Django 5.2.2 on 2025-06-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='posistion',
            new_name='position',
        ),
    ]
